### ISSUE TITLE
Please add a license.

### ISSUE THREAD

**Issue by stormychel** [ArchieGoodwin/AudioProcessor#1]

**Comment by ArchieGoodwin** [comment]
Added MIT section to readme

**Comment by stormychel** [comment]
You're right, but SPI still marks this as not having a license, not sure how often they update this.

<img width="846" alt="Screenshot 2023-05-18 at 15 53 19" src="https://github.com/ArchieGoodwin/AudioProcessor/assets/3184001/c4eaf189-78c9-43da-9a91-5319a4d930d1">

**Comment by ArchieGoodwin** [comment]
I guess once a day or so.

Sergey Dikarev

https://wilder.dev
