### ISSUE TITLE
LICENSE or LICENSE.md missing

### ISSUE THREAD

**Issue by stormychel** [ArchieGoodwin/AudioProcessor#2]
You added the license to README.md, but SPR wants a separate file.

https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository

**Comment by ArchieGoodwin** [comment]
added, thank you!

**Comment by stormychel** [comment]
Welcome sir!On 21 May 2023, at 08:13, Sergey Dikarev ***@***.***> wrote:﻿
Closed #2 as completed.
